services:
  dynamodb:
    image: amazon/dynamodb-local:2.5.2
    container_name: lab6-dynamodb-local
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    ports: ["8000:8000"]

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: lab6-dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    ports: ["8001:8001"]
    depends_on: [dynamodb]

  mysql:
    image: mysql:8.0
    container_name: lab6-banking-system-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankingdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: